In [1]:
import pandas as pd

In [3]:
ventas = pd.read_csv("Desktop/ventas (1).csv")
ventas.head()

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
1         2  2026-01-12     Mouse         5               25
2         3  2026-01-15   Teclado         3               45
3         4  2026-01-18   Monitor         1              300
4         5  2026-01-20   Teclado         2               45

In [4]:
clientes = pd.read_json("Desktop/clientes.json")
len(clientes)

3

In [6]:
inventario = pd.read_excel("Desktop/inventario.xlsx")
inventario

   id_producto    nombre    categoria  stock  precio
0            1  Notebook  Electrónica     10    1200
1            2     Mouse   Accesorios     50      25
2            3   Teclado   Accesorios     30      45
3            4   Monitor  Electrónica     15     300

In [8]:
float(inventario["stock"].mean())

26.25